### ISSUE TITLE
Formal branching practice for development

### ISSUE THREAD

**Issue by artmg** [ha-warmup/warmup#17]
Hi fellow devs, I propose using a formal branching structure to make sure that we develop consistently and release when ready. I propose a [fairly standard model](https://nvie.com/posts/a-successful-git-branching-model/) except we should stick to **`dev`** and **`rc`** branchnames rather than develop and release, simply because this is what the [upstream HA core](https://github.com/home-assistant/home-assistant/branches) uses.

So to get our dev branch back up to date I have checked out the master onto a new dev branch on my fork and have submitted this as a PR #16 .

Please let me know If you agree that the proposed structure works for you (and if my PR is a valid way to come back up to date) and we can merge it and I'll write this up as a Contributor's guide.

**Comment by foxy82** [comment]
Fine by me
