### ISSUE TITLE
Ensure all scaffold details are incorporated

### ISSUE THREAD

**Issue by ha-warmup** [ha-warmup/warmup#2]
In preparation for integration into the main HA project, let's ensure that all the details recommended in the [integration scaffold](https://github.com/ha-warmup/scaffold) for HA developers

**Comment by artmg** [comment]
We need to adopt the folder structure, file naming and key content items proposed in this scaffold. If we do this as we mature the custom component it simplifies the migration into the fork of upstream HA

**Comment by artmg** [comment]
The currently agreed direction for the project #50 is not including integration into Home Assistant Core, so this scaffold will not be required for now
