### ISSUE TITLE
Can't see 4ie climate device in HA

### ISSUE THREAD

**Issue by Pansovi4** [ha-warmup/warmup#31]
Hello,

I need your help with Warmup 4ie thermostat integration in HomeAssistant.

I performed all installation steps, copied warmup folder into custom_components, placed credentials in configuration.yaml.

But all i get after restart of HA
2021-07-09 14:57:35 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration warmup which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
I can't see any *climate devices listed. 
What else can i check and where to see logs about what goes wrong?

Raspbian GNU/Linux 10 (buster)
Docker 19.03.12
core-2021.7.1
supervisor-2021.06.8

**Comment by artmg** [comment]
Good morning @Pansovi4. Ironically, that warning message means that you have _successfully installed_ the custom component: `we found a custom integration warmup` is actually a good sign for you.

You next step will be to add the climate device. Please see the example snippet from **configuration.yaml** in the [README](https://github.com/ha-warmup/warmup#home-assistant)

Good luck

**Comment by Pansovi4** [comment]
My bad, sorry, now it's all okay, up and running!
Thank you!

**Comment by artmg** [comment]
Glad you have it working! I will improve the instructions to clarify this warning is not an issue - thanks for you contribution
