### ISSUE TITLE
publishing kWh

### ISSUE THREAD

**Issue by strelniece** [ha-warmup/warmup#36]
Hi,

I noticed that the power consumption i published once per hour, but thats not the problem, the thing is that it is published  about one minute after the hour. 

Would it be possible to change that to just before the full hour?

**Comment by artmg** [comment]
Hi @strelniece thanks for your sensible suggestion. Unfortunately this is data that is updated by the vendor (WarmUp)'s API, and is beyond our control I am afraid. Sorry we could not help

**Comment by strelniece** [comment]
ah, well not much to do then. Using influxdb/grafana, so can change it programaticaly, but always better to get it correct at the source, and guess that will not happen...
