### ISSUE TITLE
New to HA and need help

### ISSUE THREAD

**Issue by Graham350z** [ha-warmup/warmup#37]
Hi

would really appreciate some help with the installation of the warmup intergration.

Being new to HA, this is the first time I have come across this type of install and am a bit confused with the following deployment.

I am hoping someone would be kind enough to run me though the how I do this step by step
do I need to use python? how exactly do I do this?

Sorry if I am being stupid, but I am confused how to deploy this custom component and what to use especially this line .... 
**cd path/to/your/config**

I would really like to install this into my HA and would appreciate any help given.

====================
_This is a Custom Component for manual inclusion in a Home Assistant Core installation (manual using Python virtual environment). Note that it is not a Custom repository for Home Assistant Operating System (HAOS) or Home Assistant Container deployments.

Deploy custom component
Then copy the contents of the warmup subfolder into custom_components in your HA config folder, e.g.:

**cd path/to/your/config**

git clone https://github.com/ha-warmup/warmup.git /tmp/warmup

remove any previous version

****rm -r ./custom_components/warmup 2>/dev/null**
**mkdir -p ./custom_components/warmup**
**cp -r /tmp/warmup/warmup/* ./custom_components/warmup****

clean up
**rm -rf /tmp/warmup/_**

===================

Regards

**Comment by Graham350z** [comment]
Hi 

Think I have sorted this out! :-)

**Comment by foxy82** [comment]
For anyone finding this take a look here: https://github.com/ha-warmup/warmup/issues/30

There is a HACS component that needs testing.
