### ISSUE TITLE
Rename warmup_cc to warmup and then move this code into Home Assistant core.

### ISSUE THREAD

**Issue by foxy82** [ha-warmup/warmup#4]
We need to split into 2 parts.
1) The home assistant component - called warmup and added to Home Assistant repo - and removed from here.
2) The third party warmup lib - which is this repo and name as per this issue: https://github.com/ha-warmup/warmup4IE/issues/1

**Comment by ha-warmup** [comment]
On 1., do we want to do some more development work with this in the form of a custom component for the time being, or are we happy to do it all on a branch of the HA fork? I was expecting to work at it a bit more before slipstreaming it into HA, but if you feel ready then we can make the move now

**Comment by artmg** [comment]
On 1, I was expecting to do a bit more development work on this using the custom component arrangement, until it was good and stable. If however you are confident that we're ready to move it into a branch of the main HA fork, then we can go ahead and do that already

**Comment by rct** [comment]
First, thanks to everyone who has been contributing to this. 

I'd like to test and help if I can. However, at the moment, I'm not sure which repo/branch to start with and what the correct configuration is. 

Given that old warmup components are broken. My suggestions are:

1. Quick note covering the current state, ideally in the master/README to make it easier to find.  Should include which repo/branch development is occurring in, where to put the files, what configuration is needed.
2. Flesh out the minimum requirements for a release -- in progress in #5 
3. What investigation and development would be required to make things stable enough so that once an HA release is done that it will be unlikely to break again soon?

**Comment by artmg** [comment]
Hi @rct thanks for offering to help out here - I have updated the master/README of **this repo** ( https://github.com/ha-warmup/warmup ) to clarify this is the one users should clone to test and run. I have also updated the instructions for configuration.yaml

Hopefully once we have the component in the main HA tree then their release team would inform devs in advance of breaking changes affecting integrations, and if there are several people with access to update the code, we should not get stuck when someone is busy with real life

**Comment by rct** [comment]
@artmg - Thank you.  I'm very happy to report my 4 thermostats are now showing in HA very nicely.  

Note: there is a small error in the install steps `warmup_cc` vs `warmup` - fixed in #11.

**Comment by artmg** [comment]
Many thanks for the PR, @rct 
I have been collecting notes in the [wiki](https://github.com/ha-warmup/warmup/wiki) about the different parts of this software. Hopefully your 3 points are now addressed. Feel free to expand on what's written there.

@foxy82 please take a look at [what I wrote on the python library](https://github.com/ha-warmup/warmup/wiki#warmup4ie-pypi-package) and let me know your views

**Comment by artmg** [comment]
The development approach for this component has settled on:

* support use as HACS Custom Repository
* leave python code copied within the custom_components folder until there is enough interest to warrant applying effort in creating a separate [PyPI package](https://github.com/ha-warmup/warmup/wiki/PyPI-package)

There is not currently enough development around this component to try and keep up with a fast-moving project like Home Assistant Code, but there should be enough interest in keeping the Home Assistant Community Store integration supported.

Please see CONTRIBUTING.md and the [documentation wiki](https://github.com/ha-warmup/warmup/wiki) for more.
