### ISSUE TITLE
Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2023.4

### ISSUE THREAD

**Issue by tcavin** [ha-warmup/warmup#42]
Hi,

First of all, thanks for this integration !

Since few weeks, during startup, I have the warning message below in the logs of ma HA instance

I don't know if it's a critical issue or not but I prefer to mention it here

Thanks for your help 

![Capture d’écran 2022-11-09 à 17 00 38](https://user-images.githubusercontent.com/3537404/200882202-0776d781-0393-477b-9a3c-c5d40afb216f.png)

***
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77 
First occurred: 16:47:54 (2 occurrences) 
Last logged: 16:47:54

Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2023.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for warmup using this method at custom_components/warmup/climate.py, line 316: return convert_temperature(
Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2023.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for warmup using this method at custom_components/warmup/climate.py, line 323: return convert_temperature(
***

**Comment by artmg** [comment]
Many thanks for reporting this, @tcavin 
You may safely disregard this warning for now, as it should not impact your usage.
However we are very grateful that you have reported this warning, as it will enable a developer to make the necessary change to the code in time for the breaking change next spring.

**Comment by kkoenen** [comment]
Hi @artmg , awesome work!

I've been working on this a bit (https://github.com/kkoenen/warmup/blob/master/warmup/climate.py).. My changes work, but it creates a problem with the standard Thermostat card as used in Home Assistant: the manual setting of the gauge-like slider is not working anymore, neither is setting the thermostat using the target temperature..

I figured maybe something wrong with min - max settings.. I'm working with 6ie thermostats, and am very willing to spend a few more hours on this. I tried to setup a Postman api call to get the access token, but keep getting syntax errors (using the right APP-token, other headers and JSON body, imho).

Is there anywhere we can discuss offline and get this puppy on the road again? (telegram, slack, anywhere, you name it).

**Comment by artmg** [comment]
Hi Kees, I appreciate all your contributions to the knowledge around this project, and your willingness to interact, to help us improve the results of this project. However there is no _one_ developer who is an expert on this integration, so my best recommendation is to place you comments / suggestions / questions directly into issues here. Alternatively, as you are happy to work on code, please raise PRs against this project, or raise issues against your own fork and reference them here. Even if your developed snippets are not 'good' enough to be integrated into the main branch, we can always hive off a dev branch to let people try out the results of any contributions that you have the time to make. If you are having issues connecting to your WarmUp devices using your own credentials, I would try and stick closer to existing code than your own home-built code, in case that includes a minor factor that you you may have overlooked. Something that you need to appreciate, however, is that Home Assistant is a fast-moving project, that sometimes makes changes that impact low-volume sub-projects like ours - so don't be surprised or disappointed when things break. Thanks again for trying to make this work better for more people. Cheers, ArtMG

**Comment by artmg** [comment]
> My changes work, but it creates a problem with the standard Thermostat card as used in Home Assistant: the manual setting of the gauge-like slider is not working anymore, neither is setting the thermostat using the target temperature..

Another thing to check, is whether it was a change in your code that broke something, or whether it was already broken. I'm not sure that all the features of the Thermostat card work properly on my 4IE, so maybe your code is not to blame?

>  I tried to setup a Postman api call to get the access token, but keep getting syntax errors (using the right APP-token, other headers and JSON body, imho).

I have seen posts mentioning charles proxy on Android to intercept API traffic from warmup's own app, but I have not seen anyone describe packet inspection around a Home Assistant instance to help you debug your postman issues. I guess you could hack `warmup4ie.py` to log the request posted and results gotten?

**Comment by artmg** [comment]
@tcavin this issue has now been worked around thanks to new code from @kkoenen so please do let us know if this issue may be closed

**Comment by artmg** [comment]
This issue appears to have been resolved in the latest release, 2023.3.19, so I will close this issue. If there are any remaining issues around min-max temperature, or other conversion anomalies, I suggest you check out #48
