### ISSUE TITLE
6ie Thermostat

### ISSUE THREAD

**Issue by thiblam** [ha-warmup/warmup#43]
Hi there 

I rebboot my 6ie and since then I have a message:
Problem found wifi connexion error (15). 

Never happened before, worked fine.  The wifi is also fine with two others 6ie in the house. 

Thanks for your help

Regards, 

Thibault

**Comment by kkoenen** [comment]
This has nothing to do with this piece of software. You should check the wifi settings on your thermostat, maybe try to reset the router or contact WarmUp support. Sorry, not an issue for this repo.

**Comment by artmg** [comment]
Thanks, I will add the 6ie to supported devices, but add those dos and don'ts. @thiblam please confirm if you resolved your issue outside of this addon.

**Comment by artmg** [comment]
Issue originates beyond the scope of this software, so advice now included in instructions - closed
