### ISSUE TITLE
Generating AccessToken Failed <Response [200]> error

### ISSUE THREAD

**Issue by Jaffacakeking** [ha-warmup/warmup#80]
Hi all,

I've just bought a Warmup Element and have set it up using the Warmup app etc.

In HA i've installed the most recent Custom Integration via HACS, added the credentials to the configuration.yaml file but get the following errors after restarting;

This error originated from a custom integration.

Logger: custom_components.warmup.warmup4ie.warmup4ie
Source: custom_components/warmup/warmup4ie/warmup4ie.py:95
integration: warmup (documentation, issues)
First occurred: 10:29:14 (15 occurrences)
Last logged: 11:03:58

generating AccessToken failed, <Response [200]>

I'm not sure if it's relevant but i also have the Tado integration which creates Climate entities?

Where am i going wrong? Any help would be greatly appreciated.

Thanks

**Comment by artmg** [comment]
If it is failing to generate an Access Token, that could well indicate an issue with the username and password that are being supplied. Please check that in your `configuation.yaml` file you have:

* an email address and password that work properly through the user interface https://my.warmup.com/login
* the proper indentation
* no trailing spaces that could confuse values
* the password does not include any spaces or special characters that could cause confusion when the file is read
* the password is not too long (do I recall someone saying a limit of 32?)

If you suspect odd characters or length issues in the password, consider changing the password temporarily to something simpler

Good luck

**Comment by Jaffacakeking** [comment]
Thanks for your response - my password was rather complex (autogenerated secure password)

Changed to something 'simpler' and it works. Should have checked that myself... 

Appreciate you support!
